auth.py
from flask import Blueprint ,request , redirect , url_for , flash , render_template
from db import session 
from sqlalchemy.exc import IntegrityError
from werkzeug.security import check_password_hash, generate_password_hash
from flask import session as flask_session
from models import Admin, Nurse
from db import Base
# from init import  login_manager


auth_blue_print = Blueprint('auth' , __name__)


@auth_blue_print.route('/register/', methods=('POST','GET'))
def register():
	if request.method == 'POST':
		
		# reterving the username and password from html form
		username = request.form['username']
		password = generate_password_hash(request.form['password'])

		error = None

		# if username  or password is  none 
		if not username:
			error = 'Username is required.'
		elif not password:
			error = 'Password is required.'

		if error is None:
			try:

				# inserting data to admin table 
				# admin = Admin(username=username, password=password)
				admin = Admin(username=username, password=password)
				session.add(admin)
				session.commit()
				# redirect(url_for('auth.login'))
				return redirect(url_for('auth.login'))

			# handling th error if user input is duplicate
			except IntegrityError as e:
				
				error = 'Username already exists.'
				
			
			finally:
				session.close()
		
		flash(error)
	return render_template('auth/register.html')
	

@auth_blue_print.route('/login/' , methods=('POST' , 'GET'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None

	#  fetching the username from Admin table
        user = session.query(Admin).filter_by(username=username).first()

        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user.password, password):
            error = 'Incorrect password.'

        if error is None:
            # adding user to flask sesssion
            flask_session['role'] = 'Admin'
            return redirect(url_for('blue_print.dashboard' , user= username))

        flash(error)

    return render_template('auth/login.html')


@auth_blue_print.route('/admin-dashboard/<user>')
def admin_dashboard(user):
	page = request.args.get('page', default=1, type=int)
	# fetching the user from database
	username = session.query(Admin).filter_by(username=user).first()
	# if username is None:
		
	# 	return 'user not found '
	# else:
	return render_template('dashboard.html' ,user = user , page = page)


@auth_blue_print.route('/logout/')
def logout():
    # Removing all the logined user form the session	
    flask_session.pop('username', None) 
    flask_session.pop('Doctor_id', None)
    flask_session.pop('Nurse_id', None)   
    return redirect(url_for('index'))

@auth_blue_print.route('/login_required/')
def login_required():
    return render_template('pls_login.html')
    

@auth_blue_print.route('/doctor_login/', methods=['POST', 'GET'])
def doctor_login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        doctor = session.query(Base.classes.Doctor).filter_by(Doctor_id=username).first()

        if doctor is None:
            flash('Doctor not found')
        elif not check_password_hash(doctor.Password, password):
            flash('Invalid password')
        else:
            flask_session['Doctor_id'] = doctor.Doctor_id  # Use 'Doctor_id' for session key
            print(flask_session.keys())
            return redirect(url_for('auth.admin_dashboard', user=username))
    return render_template('auth/Doctor_login.html')

	
@auth_blue_print.route('/doctor_registration/' , methods=['POST', 'GET'])
def doctor_registration():

	if request.method == 'POST' :

		username = request.form['username']
		password = generate_password_hash(request.form['password'])
		to_update = 'Password'
		user = session.query(Base.classes.Doctor).filter_by(Doctor_id = username).first()

		if user :

			setattr(user , to_update , password )
			session.commit()
			return render_template('success.html')
		else:
			flash('User not found')
		return render_template('success.html')
	return render_template('auth/Doctor_register.html')


@auth_blue_print.route('/nurse_login/', methods=['POST', 'GET'])
def nurse_login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        nurse = session.query(Base.classes.Nurse).filter_by(username=username).first()

        if nurse is None:
            flash('Nurse not found')
        elif not check_password_hash(nurse.Password, password):
            flash('Invalid password')
        else:
            flask_session['role'] = 'nurse'  # Use 'Nurse_id' for session key
            print(type(flask_session))
            return redirect(url_for('blue_print.dashboard', user=username))
    return render_template('auth/Nurse_login.html')

@auth_blue_print.route('/Nurse_registration/' , methods=['POST', 'GET'])
def Nurse_registration():

	if request.method == 'POST' :

		username = request.form['username']
		password = generate_password_hash(request.form['password'])
		to_update = 'Password'
		nurse =session.query(Base.classes.Nurse).filter_by(username=username).first()

		if nurse :

			setattr(nurse , to_update , password )
			session.commit()
			return render_template('success.html')
		else:
			flash('User not found')
		
	return render_template('auth/Nurse_registration.html')

@auth_blue_print.route('/chemist_login/')
def chemist_login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        chemist = session.query(Base.classes.chemist).filter_by(chemist_id=username).first()

        if chemist is None:
            flash('chemist not found')
        elif not check_password_hash(chemist.Password, password):
            flash('Invalid password')
        else:
            flask_session['chemist_id'] = chemist.chemist_id  # Use 'chemist_id' for session key
            print(flask_session.keys())
            return redirect(url_for('auth.admin_dashboard', user=username))
    return render_template('auth/chemist_login.html')

views.py
from db import session , Base
from flask import  render_template , Blueprint , request , render_template , flash ,redirect , url_for  
from sqlalchemy.exc import IntegrityError
from utils import  requires_role
import sqlalchemy
from db import session

from sqlalchemy import  text
blue_print  = Blueprint('blue_print',__name__ )

@blue_print.route('/patient_section/')
@requires_role(['Admin'])
def patient_section():
	return render_template('patient.html')


@blue_print.route('/main_page/')
@requires_role(['Admin'])
def index():
	return render_template('index.html')

@blue_print.route('/add_patient/' , methods=("POST" ,"GET"))
@requires_role(['Admin','nurse'])
def add_patient():
	
	if request.method == 'POST':

		Patient_id = request.form['Patient_id']	
		First_name = request.form['First_name']
		Last_name = request.form['Last_name']
		Gender = request.form['Gender']
		State = request.form['State']
		Age = request.form['Age']
		Contact = request.form['Contact']
		Street = request.form['Street']
		City = request.form['City']
		Postal_code = request.form.get('Postal_code')
		Doctor_id = request.form['Doctor_id']
		Ward_id = request.form.get('Ward_id')
		Attende_id = request.form.get('Attende_id')

		msg = None
		error = None 

		if Patient_id is None: 

			error = "Enter Patient Id" 
		elif Doctor_id is None :

			error  = "Enter Doctor Id"
		
		if Attende_id == '':
			Attende_id = None
		if Ward_id ==  '':
			Ward_id  = sqlalchemy.null()
		if Postal_code == '':
			Postal_code = None

		if  Street == '':
			Street = None

		if error is None: 

			try:

				patient = Base.classes.Patient(Patient_id = Patient_id , First_name = First_name  ,Last_name = Last_name , Gender = Gender , Age = Age , contact = Contact , Street = Street ,State = State , City = City , Postal_code = Postal_code , Doctor_id = Doctor_id , Ward_id = Ward_id ,Attende_id = Attende_id)

				session.add(patient)

				return render_template('success.html')
			except IntegrityError as e:
				session.rollback()
				error = 'Patient Already available '
			except sqlalchemy.exc.PendingRollbackError as e:
					session.rollback()
					render_template('error_handling.html')
			except Exception as e:
				session.rollback()
				error = 'Something went wrong'
			finally:
				session.commit()
		
		flash(error)
		
	return render_template('add_patient.html')



def search_patient(user):
	user = session.query()

@blue_print.route('/all_patients_detail/')
@requires_role(['Admin'])
def all_patient_detail():
    page = request.args.get('page', default=1, type=int)
    per_page = 10
	
    Patient = Base.classes.Patient  # Get the mapped Patient class

	# retriving all the data from db
    patients_query = session.query(Patient)

	# taotal number of patient
    total_patients = patients_query.count()

	# limiting the number of patients per page  and the offset is used to skip the data 
    patients = patients_query.limit(per_page).offset((page-1)*per_page).all()
	# patients=patients, page=page, per_page=per_page
    session.close()

    return render_template('patient_list.html',  total_patients=total_patients , patients=patients , page=page, per_page=per_page)

@blue_print.route('/patients_search/', methods=['GET' ,  "POST"])
def patients_search():
    search_query = request.args.get('search', '').strip().lower()
    
    if search_query:
        search_results = session.query(Base.classes.Patient).filter(
            text(f"LOWER(First_name) LIKE :query OR LOWER(Last_name) LIKE :query")
        ).params(query=f"%{search_query}%").all()
    else:
        search_results = []

    return render_template('patient_list.html', patients=session.query(Base.classes.Patient).all(), search_results=search_results, search_query=search_query)


@blue_print.route('/delete_patient/<int:patient_id>')
def delete_patient(patient_id):

	patient = session.query(Base.classes.Patient).filter_by(Patient_id=patient_id).first()
	if patient is not None:
		session.delete(patient)
		session.commit()
		return render_template('success.html')
	else:
		error = 'Patient Not Found'


@blue_print.route('/update_patient/<int:patient_id>' , methods=('POST' ,'GET'))
@requires_role(['Admin'])
def update_patient(patient_id):
	patient_id = patient_id

	if request.method == 'POST':

		to_update = request.form['to_update']
		updated_value = request.form['update_value']
		error = None
		

		if to_update is None :
			error = 'Enter the column name to update'
		
		if updated_value is None:
			error = 'Enter the new value for updation'
		
		if error is None:
		
			try: 
				# checking if the column exist in table Patient
				if hasattr(Base.classes.Patient, to_update):
					patient = session.query(Base.classes.Patient).filter_by(Patient_id=patient_id).first()
					
					
					
					if patient :

						# updating the patient value
						setattr(patient, to_update, updated_value)
						session.commit()	
						return render_template('success.html')
					else:
						error = 'User not found'


			except :
				error = 'Something went wrong try again'
			finally:
				session.commit()
		flash(error)
	return render_template('update_single_patient.html' ,patient = patient_id )
	
@blue_print.route('/dashboard/')
def dashboard():

	#  Doctor details 

	doctor_list = session.query(Base.classes.Doctor) 
	doctor_count = doctor_list.count()

	male_doctor = session.query(Base.classes.Doctor).filter_by(Gender='Male');
	male_doctor = male_doctor.count() 
	female_doctor = doctor_count - male_doctor 

	# Patient details
	patient_list = session.query(Base.classes.Patient)
	patient_count = patient_list.count() 

	male_patient = session.query(Base.classes.Patient).filter_by(Gender='Male');
	male_patient = male_patient.count() 

	female_patient = patient_count - male_patient 
	#  Ward details
	ward_list  = session.query(Base.classes.Ward)
	ward_count  = ward_list.count()

	return render_template('dashboard.html' , doctor = doctor_count , patient = patient_count , ward= ward_count , male_doctor=male_doctor , female_doctor = female_doctor , male_patient = male_patient , female_patient= female_patient)

templates/admin_dash.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .container-fluid {
            padding: 0;
        }

        .admin-section {
            width: 100%;
            background-color: #007bff;
            color: white;
            padding: 20px;
            text-align: center;
            min-height: 100vh;
        }

        .admin-photo {
            width: 150px;
            height: 150px;
            border-radius: 50%;
            margin: 0 auto 20px;
            display: block;
        }

        .admin-name {
            font-size: 24px;
            margin-bottom: 10px;
        }

        .button-container {
            display: flex;
            flex-direction: column;
            gap: 10px;
        }

        .button-container a {
            text-decoration: none;
        }

        .work-section {
            width: 100%;
            padding: 20px;
        }

        .work-content {
            background-color: #f9f9f9;
            padding: 20px;
            border-radius: 10px;
            min-height: 100vh;
        }

        .cool-button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007BFF;
            color: #fff;
            border: none;
            font-size: 16px;
            cursor: pointer;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        .cool-button:hover {
            background-color: #b4c7db;
            color: black;
            transition: 0.5s;
        }

        @media (min-width: 992px) {
            .admin-section {
                width: 20%;
                min-height: 100vh;
            }
            .work-section {
                width: 80%;
            }
        }
    </style>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="admin-section">
            <img src="{{ url_for('static', filename='images/admin.png') }}" alt="Admin" class="admin-photo img-fluid">
            <p class="admin-name">{{ user }}</p>
            <div class="button-container">
                <a href="{{ url_for('blue_print.dashboard') }}" class="cool-button" id="dashboard-link"> Dashboard</a>
                <a href="{{ url_for('blue_print.all_patient_detail') }}" class="cool-button" id="patients-link"> Patients</a>
                <a href="{{ url_for('doctor_blueprint.all_doctor_detail') }}" class="cool-button" id="doctors-link"> Doctors</a>
                <a href="{{ url_for('medicine_blue_print.all_medicine_detail') }}" class="cool-button" id="medical-link"> Medical</a>
                <a href="{{ url_for('ward_blueprint.all_ward_detail') }}" class="cool-button" id="ward-link"> Ward</a>
                <a href="#" class="cool-button" id="ward-link"> Nurse</a>
            </div>
        </div>
        <div class="work-section">
            <nav class="navbar navbar-expand-lg navbar-blue navbar-light p-lg-3" style="background-color: #007BFF;">
                <div class="container">
                    <a class="navbar-brand hospital" href="{{ url_for('blue_print.dashboard') }}" style="color: white; font-size: 30px;">आपका अस्पताल</a>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link btn btn-light" href="{{ url_for('auth.logout') }}">Logout</a>
                        </li>
                    </ul>
                </div>
            </nav>
            <div class="work-content" id="content-container">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

templates/delete_patient.html
<!DOCTYPE html>
<html>

<head>
    <title>Delete Patient Details</title>
    <link rel="stylesheet" href="{{url_for('static' , filename = 'patient.css')}} ">

</head>

<body>
    <h1>Delete Patient Details</h1>
    

    <form method="POST" action="/delete_patient/">
        <label for="patient_id">Patient ID:</label>
        <input  name="patient_id" id="patient_id" required placeholder="3001"/><br />

        <input type="submit" value="Delete" />
        {% with messages = get_flashed_messages() %} {% if messages %}
    <ul>
        {% for message in get_flashed_messages() %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %} {% endwith %}
    </form>

</body>

</html>

templates/error_handling.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error Page</title>
    <!-- Include your custom CSS file -->
    <style>
        /* Add your custom CSS styles here */
body {
    font-family: Arial, sans-serif;
    background-color: #f0f0f0;
    margin: 0;
    padding: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
}

.error-message {
    background-color: #fff;
    border: 1px solid #ccc;
    padding: 20px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    text-align: center;
}

    </style>
</head>
<body>
    <div class="error-message">
        <p>Some error has occurred. You are being redirected to the main page.</p>
    </div>
    <script>
        // Redirect to index.html after 5 seconds
        setTimeout(function() {
            window.location.href = "index.html";
        }, 5000);
    </script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}DASHBOARD{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static' , filename = 'style.css') }}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous" />
    <style>
        /* Custom CSS to change navbar color to blue */
        .navbar-blue {
            background-color: #007bff;
            /* Use the desired shade of blue */
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-blue navbar-light p-lg-3">
        <a class="navbar-brand text-white" href="#">आपका अस्पताल</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{{ url_for('blue_print.patient_section') }}" class="nav-link text-white">Patient</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('doctor_blueprint.doctor_section') }}" class="nav-link text-white">Doctor</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('medicine_blue_print.medecine_section') }}" class="nav-link text-white">Medicine</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('ward_blueprint.ward_section') }}" class="nav-link text-white">Ward</a>
                </li>
                <li class "nav-item">
                    <a href="{{ url_for('bill_blueprint.bill_section') }}" class="nav-link text-white">Bill</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="{{ url_for('auth.login') }}" class="nav-link text-white">Login</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('auth.register') }}" class="nav-link text-white">Register</a>
                </li>
            </ul>
        </div>
    </nav>

    


    <div class="container mt-4 d-flex justify-content-center align-items-center" style="min-height: 80vh;">
        <!-- Use Bootstrap row and columns to display images in a horizontal layout -->
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 mb-4">
                <div class="border p-2 text-center">
                    <img src="{{ url_for('static', filename='images/admin.png') }}" class="img-fluid" alt="Admin Image" style="height: 300px; width: 500px;">
                    <a href="{{ url_for('auth.login') }}">
                        <button type="button" class="btn btn-primary my-2 px-4 py-2">Admin</button>
                    </a>
                </div>
            </div>
            
            <div class="col-12 col-md-6 col-lg-4 mb-4">
                <div class="border p-2 text-center">
                    <img src="{{ url_for('static', filename='images/doctor.png') }}" class="img-fluid" alt="Admin Image" style="height: 300px; width: 500px;">
                    <a href="{{ url_for('auth.doctor_login') }}">
                        <button type="button" class="btn btn-primary my-2 px-4 py-2">डाक्साब</button>
                    </a>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4 mb-4">
                <div class="border p-2 text-center">
                    <img src="{{ url_for('static', filename='images/Nurse.png') }}" class="img-fluid" alt="Admin Image" style="height: 300px; width: 500px;">
                    <a href="{{ url_for('auth.nurse_login') }}">
                        <button type="button" class="btn btn-primary my-2 px-4 py-2">Nurse</button>
                    </a>
                </div>
            </div>

            <div class="col-12 col-md-6 col-lg-4 mb-4">
                <div class="border p-2 text-center">
                    <img src="{{ url_for('static', filename='images/Chemist.jpeg') }}" class="img-fluid" alt="Admin Image" style="height: 300px; width: 500px;">
                    <a href="{{ url_for('auth.login') }}">
                        <button type="button" class="btn btn-primary my-2 px-4 py-2">Chemist</button>
                    </a>
                </div>
            </div>
            
        </div>

        
    </div>


    <div class="container mt-4">
        <div class="row">
            {% block content %}{% endblock content %}

        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

templates/patient.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient Section</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <!-- Include Font Awesome CSS for icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <style>
        /* Add your custom styles here, if needed */
    </style>
</head>
<body>
    <div class="container mt-4">
        <h1>Patient Section</h1>
        <div class="button-container">
            <div class="row">
                <div class="col-md-6 mb-3">
                    <div class="card text-center">
                        <div class="card-body">
                            <i class="fas fa-user-plus fa-5x"></i>
                            <h5 class="card-title">Add Patient</h5>
                            <a href="{{url_for('blue_print.add_patient')}}" class="btn btn-primary">Add</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <div class="card text-center">
                        <div class="card-body">
                            <i class="fas fa-users fa-5x"></i>
                            <h5 class="card-title">All Patients</h5>
                            <a href="{{url_for('blue_print.all_patient_detail')}}" class="btn btn-primary">View All</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <a href="{{url_for('auth.logout')}}" class="btn btn-danger">Logout</a>
            </div>
        </div>
    </div>

    <!-- Include Bootstrap JS (optional) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
</body>
</html>

templates/patient_list.html
{% extends 'admin_dash.html' %}
{% block content %}
    <title>Patient List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <style>
 
h1 {
    background-color: rgb(27, 27, 27); /* Background color for the header */
    color: white; /* Text color for the header */
    padding: 10px;
    text-align: center;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 20px;
    background-color: white; /* Background color for the table */
    box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1); /* Box shadow for the table */
}

thead th {
    background-color: rgb(27, 27, 27); /* Background color for table header cells */
    color: white; /* Text color for table header cells */
    padding: 10px;
    text-align: left;
}

tbody tr:nth-child(even) {
    background-color: #f2f2f2; /* Background color for even rows */
}

tbody td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd; /* Bottom border for table cells */
}

/* Style for the search form */
#searchForm {
    text-align: right;
    margin-bottom: 20px;
}

#searchInput {
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 3px;
}

/* Style for the pagination */
.pagination {
    text-align: center;
    margin-top: 20px;
}

.pagination a {
    display: inline-block;
    padding: 5px 10px;
    margin: 0 5px;
    background-color:rgb(27, 27, 27);
    color: white;
    border-radius: 3px;
    text-decoration: none;
}

.pagination a:hover {
    background-color: rgb(27, 27, 27);
}

.pagination .disabled {
    background-color: #ccc;
    color: #666;
    cursor: not-allowed;
}
.add-patient-content {
        position: absolute;
        top: 60px;
        left: 20px;
        width: calc(80% - 40px);
        height: calc(100% - 80px);
        background: white;
        border: 1px solid #ccc;
        padding: 20px;
        overflow: auto;
        display: none;
    }
    @media (max-width: 768px) {
        table {
            font-size: 14px; /* Reduce font size for smaller screens */
        }
        th, td {
            padding: 6px; /* Reduce padding for table cells on smaller screens */
        }
        #add-patient {
            margin-left: 10px; /* Adjust the position of the "Add Patient" button */
        }
    }

    /* Media query for screens smaller than 576px (mobile devices) */
    @media (max-width: 576px) {
        h1 {
            font-size: 24px; /* Reduce header font size for mobile devices */
        }
        table {
            font-size: 12px; /* Further reduce font size for smaller screens */
        }
        th, td {
            padding: 4px; /* Further reduce padding for table cells on smaller screens */
        }
        #add-patient {
            margin-left: 5px; /* Further adjust the position of the "Add Patient" button */
        }
    }
    </style>
</head>
<body>
<div id="admission-form">
    <h1>Patient List 

        <a href="{{url_for('blue_print.add_patient')}}" id="add-patient">
            <i class="bi bi-person-plus-fill" style="color: white; margin-left: 940px;"></i>
        </a>
    </h1>
    

    <table>
        <thead>
            <tr>
                <th>Patient ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Gender</th>
                <th>Age</th>
                <th>Contact</th>
                <th>Street</th>
                <th>State</th>
                <th>City</th>
                <th>Postal Code</th>
                <th>Doctor ID</th>
                <th>Ward ID</th>
                <th>Attendant ID</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for patients in patients %}
            <tr>
                <td>{{ patients.Patient_id }}</td>
                <td>{{ patients.First_name }}</td>
                <td>{{ patients.Last_name }}</td>
                <td>{{ patients.Gender }}</td>
                <td>{{ patients.Age }}</td>
                <td>{{ patients.contact }}</td>
                <td>{{ patients.Street }}</td>
                <td>{{ patients.State }}</td>
                <td>{{ patients.City }}</td>
                <td>{{ patients.Postal_code }}</td>
                <td>{{ patients.Doctor_id }}</td>
                <td>{{ patients.Ward_id }}</td>
                <td>{{ patients.Attende_id }}</td>
                <td> 
                    <a href="{{ url_for('blue_print.update_patient', patient_id=patients.Patient_id) }}">edit</a> | 
                    <a href="{{ url_for('blue_print.delete_patient', patient_id=patients.Patient_id) }}" onclick="return confirmDelete(event)">delete</a> 
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="pagination text-center"> <!-- Added the 'text-center' class to center content horizontally -->
    <span>Page {{ page }} of {{ total_patients // per_page + 1 }}</span>
    {% if page > 1 %}
        <a href="{{ url_for('blue_print.all_patient_detail', page=page-1) }}" id="prev">Previous</a>
    {% endif %}
    {% if page * per_page < total_patients %}
        <a href="{{ url_for('blue_print.all_patient_detail', page=page+1) }}">Next</a>
    {% endif %}
</div>
    <script>
        function confirmDelete(event) {
            if (!confirm("Are you sure you want to delete this patient")) {
                event.preventDefault(); // Prevent the default link behavior
            }
        }

    </script>
   
 

   {% endblock %}
</body>
</html>